import {getAuth} from 'firebase-admin/auth';
import {identity,validateCategory,validateEvaluation,evaluationReport,fullyApproved} from './academic-domain.mjs';
export const academicAdminActions=['listAccounts','assignJudge','listCategories','saveCategory','deleteCategory','savePoster','getEvaluationReport','downloadEvaluationReport'];
export async function academicAction(d,request,x){
 const {db,ref,dataOf,auth,admin,stamp,hash,job,bridge,randomUUID,validateAnswers}=x;
 const uid=()=>auth(request), account=async()=>{const u=await getAuth().getUser(uid());return u;};
 const settings=async()=>{const s=(await db.doc('settings/main').get()).data()||{};if(!s.appUrl)throw Error('Configure la URL pública de la plataforma en administración.');const u=new URL(s.appUrl);if(u.protocol!=='https:')throw Error('La URL pública requiere HTTPS.');return s;};
 const emailUser=async(email,name)=>{try{return await getAuth().getUserByEmail(email);}catch(e){if(e.code!=='auth/user-not-found')throw e;try{return await getAuth().createUser({email,displayName:name});}catch(e){if(e.code==='auth/email-already-exists')return getAuth().getUserByEmail(email);throw e;}}};
 const enqueue=async(kind,payload,key=randomUUID())=>db.runTransaction(async tx=>{const jr=ref('jobs',key),old=await tx.get(jr);if(!old.exists)job(tx,key,kind,payload);});
 let result;
 switch(d.action){
 case 'registerGuest':{
  if(d.consent!==true)throw Error('Debe autorizar el tratamiento de datos.');const p=identity(d.profile),event=dataOf(await ref('publicEvents',d.eventId).get()),answers=validateAnswers(event.questions,d.answers),s=await settings();
  const u=await emailUser(p.email,p.name),rr=ref('registrations',hash(`${u.uid}_${event.id}`));
  const trackingUrl=await getAuth().generateSignInWithEmailLink(p.email,{url:s.appUrl,handleCodeInApp:true});
  await db.runTransaction(async tx=>{const old=await tx.get(rr),ar=ref('accounts',u.uid),a=await tx.get(ar);if(old.exists)return;const r={...p,uid:u.uid,eventId:event.id,answers,status:'pending',payment:'pending',version:event.version,createdAt:stamp(),consentAt:stamp()};tx.create(rr,r);if(!a.exists)tx.create(ar,{...p,uid:u.uid,activated:false,createdAt:stamp()});job(tx,`registration_${rr.id}`,'registration',{...r,registrationId:rr.id,eventTitle:event.title,trackingUrl});});result={ok:true,message:'Revise su correo para consultar su propuesta.'};break;
 }
 case 'requestAccess':{
  const email=String(d.email||'').trim().toLowerCase();if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Escriba un correo válido.');const s=await settings();let u;try{u=await getAuth().getUserByEmail(email);}catch(e){if(e.code!=='auth/user-not-found')throw e;result={ok:true};break;}
  const regs=await db.collection('registrations').where('uid','==',u.uid).limit(1).get(),a=(await ref('accounts',u.uid).get()).data();if(!regs.empty||a?.role==='judge'){const trackingUrl=await getAuth().generateSignInWithEmailLink(email,{url:s.appUrl,handleCodeInApp:true});await enqueue('access',{email,name:u.displayName||a?.name||'Participante',trackingUrl,eventId:'accounts'},`access_${hash(email)}_${Math.floor(Date.now()/60000)}`);}result={ok:true};break;
 }
 case 'myProfile':{const u=await account();result=(await ref('accounts',u.uid).get()).data()||{uid:u.uid,email:u.email,name:u.displayName||u.email,role:request.auth.token.admin?'admin':'attendee',activated:true};break;}
 case 'activateAccount':{const u=await account(),ar=ref('accounts',u.uid);await db.runTransaction(async tx=>{const a=await tx.get(ar),rs=await tx.get(db.collection('registrations').where('uid','==',u.uid));if(a.data()?.role!=='judge'&&!rs.docs.some(s=>fullyApproved(s.data())))throw Error('La cuenta se activa después de aprobar la inscripción y el pago.');tx.set(ar,{uid:u.uid,email:u.email,name:a.data()?.name||u.displayName||u.email,role:a.data()?.role||rs.docs.find(s=>fullyApproved(s.data()))?.data().role||'attendee',activated:true,updatedAt:stamp()},{merge:true});});result={ok:true};break;}
 case 'listAccounts':admin(request);result=await x.page('accounts',d);break;
 case 'assignJudge':{
  admin(request);const email=String(d.email||'').trim().toLowerCase(),name=String(d.name||'').trim();if(!name||name.length>160||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Nombre y correo válidos requeridos.');const s=await settings(),u=await emailUser(email,name);if(u.customClaims?.admin)throw Error('La cuenta administradora no se modifica.');const rawLink=await getAuth().generatePasswordResetLink(email,{url:s.appUrl}),url=new URL(s.appUrl);url.searchParams.set('mode','resetPassword');url.searchParams.set('oobCode',new URL(rawLink).searchParams.get('oobCode'));const activationUrl=url.href;await ref('accounts',u.uid).set({uid:u.uid,email,name,role:'judge',updatedAt:stamp()},{merge:true});await enqueue('judgeInvitation',{uid:u.uid,email,name,eventId:'accounts',activationUrl});result={uid:u.uid,email,name,role:'judge'};break;
 }
 case 'listCategories':{admin(request);const out=await x.page('categories',d,'eventId',d.eventId);out.items=out.items.filter(c=>!c.deleted);result=out;break;}
 case 'saveCategory':{admin(request);const c=d.category,clean=validateCategory(c);dataOf(await ref('events',c.eventId).get());const cr=c.id?ref('categories',c.id):db.collection('categories').doc();await db.runTransaction(async tx=>{const old=await tx.get(cr);if(old.exists&&(old.data().eventId!==c.eventId||old.data().deleted))throw Error('Categoría no disponible.');tx.set(cr,{...clean,eventId:c.eventId,updatedAt:stamp()});});result=dataOf(await cr.get());break;}
 case 'deleteCategory':{admin(request);const cr=ref('categories',d.categoryId);dataOf(await cr.get());await cr.update({deleted:true,updatedAt:stamp()});result={ok:true};break;}
 case 'listPosters':{
  const who=uid();let q=db.collection('posters');if(d.eventId)q=q.where('eventId','==',d.eventId);if(!request.auth.token.admin){const a=(await ref('accounts',who).get()).data();q=a?.role==='judge'?q.where('judgeIds','array-contains',who):q.where('authorUid','==',who);}q=q.orderBy(x.FieldPath.documentId()).limit(250);if(d.cursor)q=q.startAfter(d.cursor);const rows=await q.get();const items=await Promise.all(rows.docs.map(async s=>{const p=dataOf(s),es=await s.ref.collection('evaluations').get();return {...p,evaluations:es.docs.map(dataOf).filter(e=>request.auth.token.admin||e.judgeUid===who)};}));result={items,nextCursor:rows.size===250?rows.docs.at(-1).id:null};break;
 }
 case 'savePoster':{
  admin(request);const p=d.poster;if(!p.title?.trim()||p.title.length>200||!Array.isArray(p.judgeIds)||!p.judgeIds.length||p.judgeIds.length>20||new Set(p.judgeIds).size!==p.judgeIds.length)throw Error('Seleccione título y jurados válidos.');if(p.url&&(p.url.length>2000||new URL(p.url).protocol!=='https:'))throw Error('El enlace del póster requiere HTTPS.');const pr=p.id?ref('posters',p.id):db.collection('posters').doc();await db.runTransaction(async tx=>{const [cs,rs,old,es,...judges]=await Promise.all([tx.get(ref('categories',p.categoryId)),tx.get(ref('registrations',p.authorRegistrationId)),tx.get(pr),tx.get(pr.collection('evaluations').limit(1)),...p.judgeIds.map(i=>tx.get(ref('accounts',i)))]);const c=dataOf(cs),r=dataOf(rs);if(c.deleted||c.eventId!==p.eventId||r.eventId!==p.eventId||r.role!=='poster'||!fullyApproved(r)||p.judgeIds.includes(r.uid)||judges.some(s=>!s.exists||s.data().role!=='judge'))throw Error('Seleccione categoría, autor aprobado y jurados válidos distintos del autor.');if(old.exists&&(old.data().eventId!==p.eventId||!es.empty))throw Error('Un póster con evaluaciones conserva su rúbrica y asignaciones.');tx.set(pr,{eventId:p.eventId,title:p.title.trim(),url:p.url||'',authorRegistrationId:r.id,authorUid:r.uid,authorName:r.name,categoryId:c.id,rubric:c,judgeIds:p.judgeIds,reportStatus:'pending',updatedAt:stamp()});});result=dataOf(await pr.get());break;
 }
 case 'submitEvaluation':{
  const who=uid(),pr=ref('posters',d.posterId),er=pr.collection('evaluations').doc(who);await db.runTransaction(async tx=>{const [ps,as,old,es]=await Promise.all([tx.get(pr),tx.get(ref('accounts',who)),tx.get(er),tx.get(pr.collection('evaluations'))]);const p=dataOf(ps);if(as.data()?.role!=='judge'||!p.judgeIds.includes(who))throw Error('Solo el jurado asignado puede evaluar este póster.');if(old.exists)throw Error('La evaluación ya fue enviada.');const e={...validateEvaluation(p.rubric,d.scores,d.comments||''),judgeUid:who,judgeName:as.data().name,posterId:p.id,createdAt:stamp()};tx.create(er,e);tx.update(pr,{evaluationCount:es.size+1});const report=evaluationReport(p,[...es.docs.map(dataOf),e]);if(report.final){tx.update(pr,{reportStatus:'queued'});job(tx,`evaluation_${p.id}`,'evaluation',report);}});result=dataOf(await er.get());break;
 }
 case 'getEvaluationReport':{admin(request);const pr=ref('posters',d.posterId),p=dataOf(await pr.get()),es=await pr.collection('evaluations').get();result=evaluationReport(p,es.docs.map(dataOf));break;}
 case 'downloadEvaluationReport':{admin(request);const p=dataOf(await ref('posters',d.posterId).get());if(p.reportStatus!=='ready'||!p.reportFileId)throw Error('El formato aún no está disponible en Drive.');result=await bridge('downloadEvaluation',{posterId:p.id,fileId:p.reportFileId});break;}
 case 'mySpeakerConferences':{
  const who=uid(),rs=await db.collection('registrations').where('uid','==',who).get();const items=[];for(const rsDoc of rs.docs){const r=rsDoc.data();if(r.role!=='speaker'||!fullyApproved(r))continue;const cs=await db.collection('conferences').where('speakerRegistrationId','==',rsDoc.id).get();for(const s of cs.docs){const c=dataOf(s),secret=(await ref('conferenceSecrets',c.id).get()).data();items.push({...c,attendanceCode:secret?.code||''});}}result=items;break;
 }
 default:return {handled:false};
 }return {handled:true,result};
}
