import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createHmac} from 'node:crypto';
const source=await readFile(new URL('../apps-script/Code.gs',import.meta.url),'utf8');
function environment(){const sheets=new Map(),props={SPREADSHEET_ID:'book',EVIDENCE_FOLDER_ID:'e',CERTIFICATE_FOLDER_ID:'c',BRIDGE_SECRET:'test-secret-with-at-least-32-characters'},memo=new Map();const counters={send:0,drafts:0,labels:0,quota:100,sendError:false,labelError:false};
 const sheet=()=>({rows:[],appendRow(r){this.rows.push([...r])},getDataRange(){return {getValues:()=>this.rows.map(r=>[...r])}},setFrozenRows(){},getRange(row,col,n,width){return {setBackground(){return this},setFontColor(){return this},setValues:v=>{this.rows[row-1]=[...v[0]]}}}});
 const book={getSheetByName:n=>sheets.get(n),insertSheet:n=>{const s=sheet();sheets.set(n,s);return s}};
 const context=vm.createContext({console,Date,JSON,PropertiesService:{getScriptProperties:()=>({getProperties:()=>props,getProperty:k=>props[k],deleteProperty:k=>delete props[k]})},SpreadsheetApp:{openById:()=>book,flush(){}},MailApp:{getRemainingDailyQuota:()=>counters.quota},GmailApp:{createDraft(){counters.drafts++;return {getId:()=>`draft-${counters.drafts}`,send(){counters.send++;if(counters.sendError)throw Error('Respuesta interrumpida');return {getId:()=>`message-${counters.send}`}}}},getMessageById:()=>({getThread:()=>({addLabel(){if(counters.labelError)throw Error('Etiqueta no disponible');counters.labels++}})}),getUserLabelByName:()=>({}),createLabel:()=>({})},Utilities:{computeHmacSha256Signature:(text,secret)=>[...createHmac('sha256',secret).update(text).digest()]},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},CacheService:{getScriptCache:()=>({get:k=>memo.get(k),put:(k,v)=>memo.set(k,v)})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this}})}});
 vm.runInContext(source,context);return {context,counters,sheets,props};}
const payload={jobId:'registration_123',kind:'registration',registrationId:'r1',eventId:'e1',eventTitle:'Evento',name:'Persona',email:'prueba@example.com',status:'pending',payment:'pending',createdAt:'2026-10-08T00:00:00Z',version:1,answers:{organization:'=HYPERLINK("x")'},settings:{organizer:'Organizador',label:'Inscripciones',ccEmail:'copia@example.com'}};
test('Google: la confirmación se envía una vez y se respalda',()=>{const {context,counters,sheets}=environment();context.processJob_(payload);context.processJob_(payload);assert.equal(counters.send,1);assert.equal(counters.labels,1);assert.equal(sheets.get('Inscripciones').rows.length,2);assert.equal(sheets.get('Respuestas').rows.length,2);});
test('Google: un envío incierto queda en revisión sin reenvío automático',()=>{const {context,counters}=environment();counters.sendError=true;assert.equal(context.processJob_(payload).review,true);counters.sendError=false;assert.equal(context.processJob_(payload).review,true);assert.equal(counters.send,1);});
test('Google: error de etiqueta se reintenta sin repetir correo',()=>{const {context,counters}=environment();counters.labelError=true;assert.throws(()=>context.processJob_(payload),/Etiqueta/);counters.labelError=false;assert.equal(context.processJob_(payload).done,true);assert.equal(counters.send,1);});
test('Google: falta de cuota no crea ni envía un borrador',()=>{const {context,counters}=environment();counters.quota=0;assert.throws(()=>context.processJob_(payload),/Cuota/);assert.equal(counters.drafts,0);assert.equal(counters.send,0);});
test('Google: confirmación atrasada no sobrescribe el estado más reciente',()=>{const {context,sheets}=environment();context.processJob_({...payload,jobId:'status_1',kind:'status',status:'approved',updatedAt:'2026-10-08T02:00:00Z'});context.processJob_(payload);assert.equal(sheets.get('Inscripciones').rows[1][5],'approved');});
test('Google: firma válida acepta y firma falsificada rechaza',()=>{const {context,props}=environment();const body=JSON.stringify({action:'job',payload}),ts=Date.now(),nonce='abcdefgh-12345678-abcdefgh';const envelope={body,ts,nonce,signature:createHmac('sha256',props.BRIDGE_SECRET).update(`${ts}.${nonce}.${body}`).digest('hex')};assert.equal(JSON.parse(context.doPost({postData:{contents:JSON.stringify(envelope)}}).text).ok,true);envelope.signature='0'.repeat(64);assert.equal(JSON.parse(context.doPost({postData:{contents:JSON.stringify(envelope)}}).text).ok,false);});
test('Google: rechaza solicitudes caducadas y replay',()=>{const {context,props}=environment();const body=JSON.stringify({action:'job',payload}),ts=Date.now(),nonce='abcdefgh-12345678-abcdefgh';const envelope={body,ts,nonce,signature:createHmac('sha256',props.BRIDGE_SECRET).update(`${ts}.${nonce}.${body}`).digest('hex')};context.doPost({postData:{contents:JSON.stringify(envelope)}});assert.equal(JSON.parse(context.doPost({postData:{contents:JSON.stringify(envelope)}}).text).ok,false);envelope.ts-=600000;assert.equal(JSON.parse(context.doPost({postData:{contents:JSON.stringify(envelope)}}).text).ok,false);});
