import test from 'node:test';import assert from 'node:assert/strict';
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
const {init,call,login}=await import('../web/api.mjs');
test('Recorrido completo de demostración y separación de roles',async()=>{
 await init();const events=await call('listEvents'),e=events[0];
 const draft=await call('saveEvent',{event:{id:'',title:'Evento de prueba',description:'Registro por pasos',location:'Bogotá',date:'2026-11-20',questions:[{id:'type',label:'Tipo',type:'select',options:['Profesional','Estudiante'],required:true,step:1},{id:'school',label:'Universidad',type:'text',required:true,step:2,condition:{field:'type',operator:'eq',value:'Estudiante'}}]}});
 await assert.rejects(()=>call('getEvent',{eventId:draft.id}),/publicado/);
 await call('publishEvent',{eventId:draft.id});
 await call('saveEvent',{event:{...draft,title:'Cambio sin publicar'}});
 assert.equal((await call('getEvent',{eventId:draft.id})).title,'Evento de prueba');
 await login('prueba@example.com','demo',false,'Persona de prueba');
 await assert.rejects(()=>call('listRegistrations'),/administrador/);
 await assert.rejects(()=>call('register',{eventId:draft.id,answers:{type:'Estudiante'}}),/Universidad/);
 const r=await call('register',{eventId:draft.id,answers:{type:'Profesional',school:'Oculta'}});
 assert.equal(r.status,'pending');assert.equal(r.payment,'pending');assert.deepEqual(r.answers,{type:'Profesional'});
 assert.equal((await call('register',{eventId:draft.id,answers:{type:'Profesional'}})).id,r.id);
 const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]).toString('base64');
 await login('admin@example.com','demo');
 await assert.rejects(()=>call('updateRegistration',{registrationId:r.id,payment:'approved'}),/Primero/);
 await call('updateRegistration',{registrationId:r.id,status:'approved'});
 await call('saveConference',{conference:{eventId:draft.id,title:'Conferencia',speaker:'Ponente',location:'Sala',opensAt:new Date(Date.now()-60000).toISOString(),closesAt:new Date(Date.now()+60000).toISOString(),active:true}});
 const c=(await call('listConferences',{eventId:draft.id}))[0];
 await login('prueba@example.com','demo');
 await assert.rejects(()=>call('stamp',{registrationId:r.id,conferenceId:c.id,code:c.attendanceCode,base64:png,mime:'image/png',fileName:'a.png'}),/pago/);
 await login('admin@example.com','demo');await call('updateRegistration',{registrationId:r.id,payment:'approved',reference:'VERIFICADO-001'});
 await login('prueba@example.com','demo');
 const a=await call('stamp',{registrationId:r.id,conferenceId:c.id,code:c.attendanceCode,base64:png,mime:'image/png',fileName:'a.png'});
 assert.equal(a.certificateStatus,'demo');assert.equal((await call('stamp',{registrationId:r.id,conferenceId:c.id,code:c.attendanceCode,base64:png,mime:'image/png',fileName:'a.png'})).id,a.id);
 await assert.rejects(()=>call('getCertificate',{attendanceId:a.id}),/Apps Script/);
 assert.equal((await call('myAttendance')).length,1);
 await login('admin@example.com','demo');assert.equal((await call('listAttendance',{eventId:draft.id})).length,1);
 assert.equal((await call('listJobs')).filter(j=>j.kind==='certificate').length,1);
 assert.equal(e.id,'encuentro-2026');
});
