import test from 'node:test';import assert from 'node:assert/strict';
import {validateSchema} from '../web/domain.mjs';
import {sectionsFor,appearanceFor} from '../web/form-design.mjs';
const base={title:'Congreso',description:'',questions:[{id:'perfil',label:'Perfil',type:'text',required:true,step:1},{id:'detalle',label:'Detalle',type:'text',required:false,step:3}],sections:[{step:1,title:'Datos personales',description:'Queremos conocerte'},{step:3,title:'Tu participación',description:'Elige tu recorrido'}],appearance:{theme:'warm',layout:'cards',cover:'ribbon'}};
test('Las secciones mantienen el orden y los títulos personalizados con pasos no consecutivos',()=>{validateSchema(base);assert.deepEqual(sectionsFor(base).map(s=>[s.step,s.title]),[[1,'Datos personales'],[3,'Tu participación']]);assert.deepEqual(appearanceFor(base),base.appearance)});
test('Los formularios anteriores conservan una apariencia y secciones válidas',()=>{assert.equal(appearanceFor({}).theme,'studio');assert.equal(sectionsFor({questions:base.questions}).length,2)});
test('El servidor rechaza temas arbitrarios y secciones repetidas',()=>{assert.throws(()=>validateSchema({...base,appearance:{...base.appearance,theme:'url(javascript:alert(1))'}}),/Estilo/);assert.throws(()=>validateSchema({...base,sections:[base.sections[0],base.sections[0]]}),/sección/)});
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
test('Guardar un nuevo diseño en borrador no cambia el formulario público hasta republicar',async()=>{const {init,call}=await import('../web/api.mjs');await init();const form=await call('saveEvent',{event:{...structuredClone(base),id:''}});await call('publishEvent',{eventId:form.id});await call('saveEvent',{event:{...form,appearance:{theme:'midnight',layout:'minimal',cover:'none'},sections:[{step:1,title:'Cambio sin publicar',description:''},base.sections[1]]}});let published=await call('getEvent',{eventId:form.id});assert.equal(published.appearance.theme,'warm');assert.equal(published.sections[0].title,'Datos personales');await call('publishEvent',{eventId:form.id});published=await call('getEvent',{eventId:form.id});assert.equal(published.appearance.theme,'midnight');assert.equal(published.sections[0].title,'Cambio sin publicar')});
